[package]
name = "rust-lambda"
version = "0.1.0"
authors = ["aaronjeline <aeline@umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
